language: go

go:
  - "1.12.x"

env:
  - GO111MODULE=on

matrix:
  fast_finish: true

install:
  - go get golang.org/x/lint/golint

script:
  - go build
  - golint -set_exit_status ./...
  - diff -u <(echo -n) <(gofmt -d .)
