name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12

    - name: Build
      run: go build -v ./...

    - name: Lint
      run: |
        go get golang.org/x/lint/golint
        golint -set_exit_status ./...

    - name: Format
      run: diff -u <(echo -n) <(gofmt -d .)
